2017-10-15T04:20:25.794Z - error: Error when processing render request Error during rendering report: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything Error: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything
    at _require (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:44:11)
    at evalmachine.<anonymous>:2:12
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:123:6)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12) requestId=44
2017-10-15T04:20:25.797Z - error: Error during processing request: http://localhost:2000/api/report/presupuesto_ortodoncia details: Error during rendering report: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything Error: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything
    at _require (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:44:11)
    at evalmachine.<anonymous>:2:12
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:123:6)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
2017-10-15T04:21:28.832Z - error: Error when processing render request Error during rendering report: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything Error: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything
    at _require (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:44:11)
    at evalmachine.<anonymous>:2:12
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:123:6)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12) requestId=46
2017-10-15T04:21:28.834Z - error: Error during processing request: http://localhost:2000/api/report/presupuesto_ortodoncia details: Error during rendering report: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything Error: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything
    at _require (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:44:11)
    at evalmachine.<anonymous>:2:12
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:123:6)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
2017-10-15T04:28:45.970Z - error: Error when processing render request Error during rendering report: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything Error: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything
    at _require (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:44:11)
    at evalmachine.<anonymous>:2:12
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:123:6)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12) requestId=1
2017-10-15T04:28:45.972Z - error: Error during processing request: http://localhost:2000/api/report/presupuesto_ortodoncia details: Error during rendering report: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything Error: Unsupported module in scripts: http. To enable require on particular module, you need to update the configuration as {"scripts": { "allowedModules": ["http"] } } ... Alternatively you can also set "*" to allowedModules to enable everything
    at _require (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:44:11)
    at evalmachine.<anonymous>:2:12
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:123:6)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
2017-10-15T04:33:35.489Z - error: Error when processing render request Error during rendering report: data is not defined ReferenceError: data is not defined
    at getPresupuestos (evalmachine.<anonymous>:26:25)
    at IncomingMessage.result.on (evalmachine.<anonymous>:13:32)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) requestId=1
2017-10-15T04:33:35.491Z - error: Error during processing request: http://localhost:2000/api/report/presupuesto_ortodoncia details: Error during rendering report: data is not defined ReferenceError: data is not defined
    at getPresupuestos (evalmachine.<anonymous>:26:25)
    at IncomingMessage.result.on (evalmachine.<anonymous>:13:32)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2017-10-15T04:35:41.707Z - error: Error when processing render request Error during rendering report: data is not defined ReferenceError: data is not defined
    at getPresupuestos (evalmachine.<anonymous>:26:25)
    at IncomingMessage.result.on (evalmachine.<anonymous>:13:32)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) requestId=4
2017-10-15T04:35:41.709Z - error: Error during processing request: http://localhost:2000/api/report/presupuesto details: Error during rendering report: data is not defined ReferenceError: data is not defined
    at getPresupuestos (evalmachine.<anonymous>:26:25)
    at IncomingMessage.result.on (evalmachine.<anonymous>:13:32)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2017-10-15T04:43:56.872Z - error: Error when processing render request Error during rendering report: alert is not defined ReferenceError: alert is not defined
    at beforeRender (evalmachine.<anonymous>:18:5)
    at evalmachine.<anonymous>:48:111
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:123:6)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12) requestId=11
2017-10-15T04:43:56.872Z - error: Error during processing request: http://localhost:2000/api/report/presupuesto details: Error during rendering report: alert is not defined ReferenceError: alert is not defined
    at beforeRender (evalmachine.<anonymous>:18:5)
    at evalmachine.<anonymous>:48:111
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-scripts\lib\scriptEvalChild.js:123:6)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
2017-10-15T05:25:52.223Z - error: uncaughtException: "listener" argument must be a function date=Sun Oct 15 2017 02:25:52 GMT-0300 (Hora verano Sudamérica Pacífico), pid=1140, uid=null, gid=null, cwd=C:\Users\Alink\Desktop\sistema_dental, execPath=C:\Program Files\nodejs\node.exe, version=v6.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Alink\Desktop\sistema_dental], rss=164544512, heapTotal=147341312, heapUsed=91945920, external=19620114, loadavg=[0, 0, 0], uptime=1095747.6776282, trace=[column=11, file=events.js, function=_addListener, line=216, method=null, native=false, column=10, file=events.js, function=IncomingMessage.addListener, line=275, method=addListener, native=false, column=35, file=_stream_readable.js, function=IncomingMessage.Readable.on, line=687, method=on, native=false, column=16, file=C:\Users\Alink\Desktop\sistema_dental\common\models\tratamiento.js, function=ClientRequest.http.get, line=21, method=get, native=false, column=16, file=events.js, function=ClientRequest.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=ClientRequest.emit, line=188, method=emit, native=false, column=21, file=_http_client.js, function=HTTPParser.parserOnIncomingClient [as onIncoming], line=474, method=parserOnIncomingClient [as onIncoming], native=false, column=23, file=_http_common.js, function=HTTPParser.parserOnHeadersComplete, line=99, method=parserOnHeadersComplete, native=false, column=20, file=_http_client.js, function=Socket.socketOnData, line=363, method=socketOnData, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=18, file=_stream_readable.js, function=readableAddChunk, line=176, method=null, native=false, column=10, file=_stream_readable.js, function=Socket.Readable.push, line=134, method=push, native=false, column=20, file=net.js, function=TCP.onread, line=548, method=onread, native=false], stack=[TypeError: "listener" argument must be a function,     at _addListener (events.js:216:11),     at IncomingMessage.addListener (events.js:275:10),     at IncomingMessage.Readable.on (_stream_readable.js:687:35),     at ClientRequest.http.get (C:\Users\Alink\Desktop\sistema_dental\common\models\tratamiento.js:21:16),     at ClientRequest.g (events.js:291:16),     at emitOne (events.js:96:13),     at ClientRequest.emit (events.js:188:7),     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21),     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23),     at Socket.socketOnData (_http_client.js:363:20),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at readableAddChunk (_stream_readable.js:176:18),     at Socket.Readable.push (_stream_readable.js:134:10),     at TCP.onread (net.js:548:20)]
2017-10-15T05:39:12.454Z - error: Error when processing render request Error during rendering report: Recipe must be specified Error: Recipe must be specified
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\lib\render\render.js:104:13
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=1
2017-10-15T05:40:18.784Z - error: Error when processing render request Error during rendering report: Recipe must be specified Error: Recipe must be specified
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\lib\render\render.js:104:13
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=2
2017-10-15T05:42:19.085Z - error: Error when processing render request Error during rendering report: Recipe must be specified Error: Recipe must be specified
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\lib\render\render.js:104:13
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=3
2017-10-15T06:12:54.914Z - error: Error when processing render request Error during rendering report: Unauthorized Error: Unauthorized
    at MemoryCollection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-public-templates\lib\main.js:257:19)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:171:33
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:151:16
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=1
2017-10-15T06:14:55.273Z - error: Error when processing render request Error during rendering report: Unauthorized Error: Unauthorized
    at MemoryCollection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-public-templates\lib\main.js:257:19)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:171:33
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:151:16
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=4
2017-10-15T06:15:12.702Z - error: Error when processing render request Error during rendering report: Unauthorized Error: Unauthorized
    at MemoryCollection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-public-templates\lib\main.js:257:19)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:171:33
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:151:16
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=5
2017-10-15T06:18:31.233Z - error: Error when processing render request Error during rendering report: Unauthorized Error: Unauthorized
    at MemoryCollection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-public-templates\lib\main.js:257:19)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:171:33
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:151:16
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=6
2017-10-15T06:26:25.518Z - error: Error during processing request: http://localhost:2000/api/validate-import details: invalid signature: 0x746e495b Error: invalid signature: 0x746e495b
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\unzip2\lib\parse.js:63:13
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-10-15T06:26:31.848Z - error: Error during processing request: http://localhost:2000/api/import details: invalid signature: 0x746e495b Error: invalid signature: 0x746e495b
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\unzip2\lib\parse.js:63:13
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-10-15T06:26:32.677Z - error: Error during processing request: http://localhost:2000/api/import details: invalid signature: 0x746e495b Error: invalid signature: 0x746e495b
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\unzip2\lib\parse.js:63:13
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-10-15T06:30:01.193Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\edcf99b31badbdc6b370e57759a3d8fa'
    at Error (native)
2017-10-15T06:30:31.193Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\b43c35b6689ab1239fe139eeeda9dbeb'
    at Error (native)
2017-10-15T06:31:01.190Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\b43c35b6689ab1239fe139eeeda9dbeb'
    at Error (native)
2017-10-15T06:31:31.189Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\b43c35b6689ab1239fe139eeeda9dbeb'
    at Error (native)
2017-10-15T06:32:01.190Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\b43c35b6689ab1239fe139eeeda9dbeb'
    at Error (native)
2017-10-15T06:32:31.195Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\b43c35b6689ab1239fe139eeeda9dbeb'
    at Error (native)
2017-10-15T06:33:01.186Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\b43c35b6689ab1239fe139eeeda9dbeb'
    at Error (native)
2017-10-15T06:33:31.187Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\d9ba322416af87f232bd431184f4651d'
    at Error (native)
2017-10-15T06:34:01.186Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\b43c35b6689ab1239fe139eeeda9dbeb'
    at Error (native)
2017-10-15T06:34:31.187Z - error:  Error: EPERM: operation not permitted, stat 'C:\Users\Alink\AppData\Local\Temp\jsreport-temp\b43c35b6689ab1239fe139eeeda9dbeb'
    at Error (native)
2017-10-15T06:42:38.272Z - error: exec error: Error: spawn fop.bat ENOENT requestId=1
2017-10-15T06:42:48.081Z - error: exec error: Error: spawn fop.bat ENOENT requestId=2
2017-10-15T20:57:23.690Z - error: Failed to load collection images Error: Unable to parse config.json. Database is corrupted or you are trying to use "fs" jsreportstore provider on the data set created with "nedb" provider. Please switch connection string name to nedb and npm install jsreport-embedded-store 
Error: ENOENT: no such file or directory, open 'C:\Users\Alink\Desktop\sistema_dental\data\images\23695606.png\config.json'
    at ReadFileContext.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-fs-store\lib\persistence.js:304:17)
    at ReadFileContext.callback (C:\Users\Alink\Desktop\sistema_dental\node_modules\graceful-fs\graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
2017-10-15T20:57:23.693Z - error: Error occured during reporter init Error: Unable to parse config.json. Database is corrupted or you are trying to use "fs" jsreportstore provider on the data set created with "nedb" provider. Please switch connection string name to nedb and npm install jsreport-embedded-store 
Error: ENOENT: no such file or directory, open 'C:\Users\Alink\Desktop\sistema_dental\data\images\23695606.png\config.json'
    at ReadFileContext.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-fs-store\lib\persistence.js:304:17)
    at ReadFileContext.callback (C:\Users\Alink\Desktop\sistema_dental\node_modules\graceful-fs\graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
2017-10-21T16:37:18.895Z - error: Error when processing render request Error during rendering report: Command failed: /Users/Nicolas/Desktop/dental/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/Nicolas/Desktop/dental/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/1w/dl1f4dm113d2_80mhkn07m780000gn/T/jsreport-temp/1a920080-b67e-11e7-954b-afc2f0fbe4cesettings.html
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra Error: Command failed: /Users/Nicolas/Desktop/dental/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/Nicolas/Desktop/dental/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/1w/dl1f4dm113d2_80mhkn07m780000gn/T/jsreport-temp/1a920080-b67e-11e7-954b-afc2f0fbe4cesettings.html
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra
    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5) requestId=1
2017-10-21T16:37:18.901Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Command failed: /Users/Nicolas/Desktop/dental/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/Nicolas/Desktop/dental/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/1w/dl1f4dm113d2_80mhkn07m780000gn/T/jsreport-temp/1a920080-b67e-11e7-954b-afc2f0fbe4cesettings.html
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra Error: Command failed: /Users/Nicolas/Desktop/dental/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/Nicolas/Desktop/dental/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/1w/dl1f4dm113d2_80mhkn07m780000gn/T/jsreport-temp/1a920080-b67e-11e7-954b-afc2f0fbe4cesettings.html
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra
    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
2017-10-21T16:44:03.388Z - error: Error when processing render request Error during rendering report: Command failed: /Users/Nicolas/Desktop/dental/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/Nicolas/Desktop/dental/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/1w/dl1f4dm113d2_80mhkn07m780000gn/T/jsreport-temp/0ba453b0-b67f-11e7-94f1-e1c4fbb20d92settings.html
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra Error: Command failed: /Users/Nicolas/Desktop/dental/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/Nicolas/Desktop/dental/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/1w/dl1f4dm113d2_80mhkn07m780000gn/T/jsreport-temp/0ba453b0-b67f-11e7-94f1-e1c4fbb20d92settings.html
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra
    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12) requestId=1
2017-10-21T16:44:03.391Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Command failed: /Users/Nicolas/Desktop/dental/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/Nicolas/Desktop/dental/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/1w/dl1f4dm113d2_80mhkn07m780000gn/T/jsreport-temp/0ba453b0-b67f-11e7-94f1-e1c4fbb20d92settings.html
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra Error: Command failed: /Users/Nicolas/Desktop/dental/node_modules/phantomjs/lib/phantom/bin/phantomjs --ignore-ssl-errors=yes --web-security=false --ssl-protocol=any /Users/Nicolas/Desktop/dental/node_modules/jsreport-phantom-pdf/node_modules/phantom-html-to-pdf/lib/scripts/standaloneScript.js /var/folders/1w/dl1f4dm113d2_80mhkn07m780000gn/T/jsreport-temp/0ba453b0-b67f-11e7-94f1-e1c4fbb20d92settings.html
, Segmentation fault error: if you are using macOS Sierra with phantomjs < 2 remember that phantomjs < 2 does not work there and has bugs (https://github.com/ariya/phantomjs/issues/14558), try to upgrade to phantom 2 if using macOS Sierra
    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
2017-10-22T00:43:51.025Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Sat Oct 21 2017 21:43:51 GMT-0300 (Hora verano Sudamérica Pacífico), pid=21636, uid=null, gid=null, cwd=C:\Users\Alink\Desktop\sistema_dental, execPath=C:\Program Files\nodejs\node.exe, version=v6.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Alink\Desktop\sistema_dental], rss=130170880, heapTotal=115363840, heapUsed=81010712, external=17875500, loadavg=[0, 0, 0], uptime=1683629.1492886, trace=[column=35, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=336, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=197, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=339, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\topologies\server.js:336:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\connection.js:197:10),     at Socket.g (events.js:291:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:339:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
2017-10-30T01:19:43.259Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Oct 29 2017 22:19:43 GMT-0300 (Hora verano Sudamérica Pacífico), pid=27564, uid=null, gid=null, cwd=C:\Users\Alink\Desktop\sistema_dental, execPath=C:\Program Files\nodejs\node.exe, version=v6.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Alink\Desktop\sistema_dental], rss=130920448, heapTotal=115363840, heapUsed=88976576, external=17875500, loadavg=[0, 0, 0], uptime=2376991.6509961, trace=[column=35, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=336, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=emitErrorNT, line=1278, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\topologies\server.js:336:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\connection.js:187:49),     at Socket.g (events.js:291:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at emitErrorNT (net.js:1278:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
2017-10-30T03:52:31.252Z - error: Error when processing render request Error during rendering report: Unauthorized Error: Unauthorized
    at EmbeddedCollection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-public-templates\lib\main.js:257:19)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:171:33
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:151:16
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=10
2017-10-30T03:56:18.693Z - error: Error when processing render request Error during rendering report: Unauthorized Error: Unauthorized
    at EmbeddedCollection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-public-templates\lib\main.js:257:19)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:171:33
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:151:16
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=11
2017-10-30T03:56:55.674Z - error: Error when processing render request Error during rendering report: Unauthorized Error: Unauthorized
    at EmbeddedCollection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-public-templates\lib\main.js:257:19)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:171:33
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\lib\listenerCollection.js:151:16
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=12
2017-10-30T04:03:45.884Z - error: Error when processing render request Error during rendering report: Cannot read property 'toLocaleString' of undefined TypeError: Cannot read property 'toLocaleString' of undefined
    at Object.formatear (evalmachine.<anonymous>:2:18)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:8:76)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=17
2017-10-30T04:03:45.886Z - error: Error during processing request: http://localhost:2000/api/report details: Error during rendering report: Cannot read property 'toLocaleString' of undefined TypeError: Cannot read property 'toLocaleString' of undefined
    at Object.formatear (evalmachine.<anonymous>:2:18)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:8:76)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-03T00:19:52.364Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Thu Nov 02 2017 21:19:52 GMT-0300 (Hora verano Sudamérica Pacífico), pid=7500, uid=null, gid=null, cwd=C:\Users\Alink\Desktop\sistema_dental, execPath=C:\Program Files\nodejs\node.exe, version=v6.10.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Alink\Desktop\sistema_dental], rss=131366912, heapTotal=116412416, heapUsed=89095248, external=17875500, loadavg=[0, 0, 0], uptime=2719007.1535848, trace=[column=35, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=336, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=291, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=197, method=null, native=false, column=16, file=events.js, function=Socket.g, line=291, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=339, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\topologies\server.js:336:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:291:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\mongodb-core\lib\connection\connection.js:197:10),     at Socket.g (events.js:291:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:339:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
2017-11-03T00:52:17.063Z - error: Error when processing render request Error during rendering report: Asset /metro.min.css not found Error: Asset /metro.min.css not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=17
2017-11-03T00:52:17.066Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Asset /metro.min.css not found Error: Asset /metro.min.css not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-03T00:52:25.378Z - error: Error when processing render request Error during rendering report: Asset assets/metro.min.css not found Error: Asset assets/metro.min.css not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=18
2017-11-03T00:52:25.380Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Asset assets/metro.min.css not found Error: Asset assets/metro.min.css not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-03T00:52:26.353Z - error: Error when processing render request Error during rendering report: Asset assets/metro.min.css not found Error: Asset assets/metro.min.css not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=19
2017-11-03T00:52:26.355Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Asset assets/metro.min.css not found Error: Asset assets/metro.min.css not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-03T00:56:31.582Z - error: Error when processing render request Error during rendering report: Asset  not found Error: Asset  not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=44
2017-11-03T00:56:31.583Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Asset  not found Error: Asset  not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-03T00:58:35.490Z - error: Error when processing render request Error during rendering report: Asset  not found Error: Asset  not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=1
2017-11-03T00:58:35.492Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Asset  not found Error: Asset  not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-03T01:00:37.012Z - error: Error when processing render request Error during rendering report: Unsupported asset encoding param value css, supported values are base64, utf8, link, dataURI and string Error: Unsupported asset encoding param value css, supported values are base64, utf8, link, dataURI and string
    at convert (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:50:15)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:63:26
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:731:9)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:71:11)
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-images\node_modules\bluebird\js\release\promisify.js:1:0), <anonymous>:13:39)
    at evaluateAssets (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:66:10)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:267:14
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=4
2017-11-03T01:00:37.013Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Unsupported asset encoding param value css, supported values are base64, utf8, link, dataURI and string Error: Unsupported asset encoding param value css, supported values are base64, utf8, link, dataURI and string
    at convert (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:50:15)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:63:26
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:731:9)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:71:11)
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-images\node_modules\bluebird\js\release\promisify.js:1:0), <anonymous>:13:39)
    at evaluateAssets (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:66:10)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:267:14
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-03T01:00:49.247Z - error: Error when processing render request Error during rendering report: Asset encoded as dataURI needs to have file extension jpeg|jpg|gif|png|svg|woff|tff|otf|woff2|eot Error: Asset encoded as dataURI needs to have file extension jpeg|jpg|gif|png|svg|woff|tff|otf|woff2|eot
    at convert (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:54:15)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:63:26
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:731:9)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:71:11)
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-images\node_modules\bluebird\js\release\promisify.js:1:0), <anonymous>:13:39)
    at evaluateAssets (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:66:10)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:267:14
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=5
2017-11-03T01:00:49.249Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Asset encoded as dataURI needs to have file extension jpeg|jpg|gif|png|svg|woff|tff|otf|woff2|eot Error: Asset encoded as dataURI needs to have file extension jpeg|jpg|gif|png|svg|woff|tff|otf|woff2|eot
    at convert (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:54:15)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:63:26
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:731:9)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:71:11)
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-images\node_modules\bluebird\js\release\promisify.js:1:0), <anonymous>:13:39)
    at evaluateAssets (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:66:10)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:267:14
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-03T01:00:55.388Z - error: Error when processing render request Error during rendering report: Unsupported asset encoding param value css, supported values are base64, utf8, link, dataURI and string Error: Unsupported asset encoding param value css, supported values are base64, utf8, link, dataURI and string
    at convert (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:50:15)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:63:26
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:731:9)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:71:11)
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-images\node_modules\bluebird\js\release\promisify.js:1:0), <anonymous>:13:39)
    at evaluateAssets (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:66:10)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:267:14
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=6
2017-11-03T01:00:55.390Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Unsupported asset encoding param value css, supported values are base64, utf8, link, dataURI and string Error: Unsupported asset encoding param value css, supported values are base64, utf8, link, dataURI and string
    at convert (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:50:15)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:63:26
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:718:13
    at async.forEachOf.async.eachOf (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:233:13)
    at _parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\node_modules\async\lib\async.js:731:9)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\async-replace\async-replace.js:71:11)
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\node_modules\bluebird\js\release\util.js:16:23)
    at ret (eval at makeNodePromisifiedEval (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-images\node_modules\bluebird\js\release\promisify.js:1:0), <anonymous>:13:39)
    at evaluateAssets (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:66:10)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:267:14
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-03T01:06:41.470Z - error: Error when processing render request Error during rendering report: Asset bootstrap.min.css/content.css not found Error: Asset bootstrap.min.css/content.css not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) requestId=15
2017-11-03T01:06:41.471Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Asset bootstrap.min.css/content.css not found Error: Asset bootstrap.min.css/content.css not found
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-assets\lib\assets.js:149:15
    at tryCatcher (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Alink\Desktop\sistema_dental\node_modules\listener-collection\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
2017-11-12T20:11:20.886Z - error: Error when processing render request Error during rendering report: Parse error on line 16115:
...blemas.linea_media1 || listado_problemas
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS' Error: Parse error on line 16115:
...blemas.linea_media1 || listado_problemas
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=66
2017-11-12T20:11:20.890Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Parse error on line 16115:
...blemas.linea_media1 || listado_problemas
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS' Error: Parse error on line 16115:
...blemas.linea_media1 || listado_problemas
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T20:11:34.768Z - error: Error when processing render request Error during rendering report: Parse error on line 16115:
...blemas.linea_media1 | listado_problemas.
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS' Error: Parse error on line 16115:
...blemas.linea_media1 | listado_problemas.
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=67
2017-11-12T20:11:34.770Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Parse error on line 16115:
...blemas.linea_media1 | listado_problemas.
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS' Error: Parse error on line 16115:
...blemas.linea_media1 | listado_problemas.
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T20:11:53.514Z - error: Error when processing render request Error during rendering report: Cannot read property 'hash' of undefined TypeError: Cannot read property 'hash' of undefined
    at Object.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:16:17)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:10:32)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=68
2017-11-12T20:11:53.516Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Cannot read property 'hash' of undefined TypeError: Cannot read property 'hash' of undefined
    at Object.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:16:17)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:10:32)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T20:13:49.218Z - error: Error when processing render request Error during rendering report: Cannot read property 'hash' of undefined TypeError: Cannot read property 'hash' of undefined
    at Object.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:16:17)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:10:32)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=69
2017-11-12T20:13:49.221Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Cannot read property 'hash' of undefined TypeError: Cannot read property 'hash' of undefined
    at Object.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:16:17)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:10:32)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T20:16:48.064Z - error: Error when processing render request Error during rendering report: Missing helper: "or" Error: Missing helper: "or"
    at Object.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\helpers\helper-missing.js:19:13)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:10:197)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=70
2017-11-12T20:16:48.065Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Missing helper: "or" Error: Missing helper: "or"
    at Object.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\helpers\helper-missing.js:19:13)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:10:197)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T22:21:33.882Z - error: Error when processing render request Error during rendering report: Parse error on line 16539:
...f plan_tratamiento == 'con_extra'}}   
-----------------------^
Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'EQUALS' Error: Parse error on line 16539:
...f plan_tratamiento == 'con_extra'}}   
-----------------------^
Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'EQUALS'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=77
2017-11-12T22:21:33.883Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Parse error on line 16539:
...f plan_tratamiento == 'con_extra'}}   
-----------------------^
Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'EQUALS' Error: Parse error on line 16539:
...f plan_tratamiento == 'con_extra'}}   
-----------------------^
Expecting 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'EQUALS'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T22:22:20.440Z - error: Error when processing render request Error during rendering report: Parse error on line 16950:
...                 {{#/if}}             
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'SEP' Error: Parse error on line 16950:
...                 {{#/if}}             
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'SEP'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=78
2017-11-12T22:22:20.442Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Parse error on line 16950:
...                 {{#/if}}             
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'SEP' Error: Parse error on line 16950:
...                 {{#/if}}             
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'SEP'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T22:22:35.188Z - error: Error when processing render request Error during rendering report: Cannot read property 'includeZero' of undefined TypeError: Cannot read property 'includeZero' of undefined
    at Object.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:16:22)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:69:32)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=79
2017-11-12T22:22:35.190Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Cannot read property 'includeZero' of undefined TypeError: Cannot read property 'includeZero' of undefined
    at Object.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\helpers\if.js:16:22)
    at Object.eval (eval at createFunctionContext (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:69:32)
    at main (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:173:32)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\runtime.js:176:12)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:525:21)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T22:33:47.664Z - error: Error when processing render request Error during rendering report: Parse error on line 16539:
...n_tratamiento.extra == "con_extra" }} 
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'EQUALS' Error: Parse error on line 16539:
...n_tratamiento.extra == "con_extra" }} 
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'EQUALS'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17) requestId=82
2017-11-12T22:33:47.666Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Parse error on line 16539:
...n_tratamiento.extra == "con_extra" }} 
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'EQUALS' Error: Parse error on line 16539:
...n_tratamiento.extra == "con_extra" }} 
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'EQUALS'
    at Object.parseError (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30)
    at HandlebarsEnvironment.parse (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19)
    at ret (C:\Users\Alink\Desktop\sistema_dental\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-handlebars\lib\handlebarsEngine.js:25:14
    at evalmachine.<anonymous>:1:41
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at ContextifyScript.Script.runInNewContext (vm.js:41:15)
    at Object.exports.runInNewContext (vm.js:72:17)
2017-11-12T22:37:09.159Z - error: Error when processing render request Error during rendering report: Unexpected token } in JSON at position 106 SyntaxError: Unexpected token } in JSON at position 106
    at Object.parse (native)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\lib\render\resolveReferences.js:4:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\lib\render\engineScript.js:96:17)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9) requestId=87
2017-11-12T22:37:09.160Z - error: Error during processing request: http://localhost:2000/api/report/reporte_ortodoncia details: Error during rendering report: Unexpected token } in JSON at position 106 SyntaxError: Unexpected token } in JSON at position 106
    at Object.parse (native)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\lib\render\resolveReferences.js:4:17)
    at module.exports (C:\Users\Alink\Desktop\sistema_dental\node_modules\jsreport-core\lib\render\engineScript.js:96:17)
    at process.<anonymous> (C:\Users\Alink\Desktop\sistema_dental\node_modules\script-manager\lib\worker-processes.js:48:36)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2018-09-16T04:12:20.636Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:12:20 GMT+0000 (UTC), pid=26, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=152580096, heapTotal=116350976, heapUsed=71028400, external=18278852, loadavg=[2.68505859375, 1.70703125, 1.380859375], uptime=8761, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:12:42.692Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:12:42 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=159989760, heapTotal=122290176, heapUsed=86195064, external=18302505, loadavg=[2.26953125, 1.6826171875, 1.3798828125], uptime=8783, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:13:07.545Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:13:07 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=151166976, heapTotal=118534144, heapUsed=80832056, external=26630091, loadavg=[2.30419921875, 1.74072265625, 1.4072265625], uptime=8808, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:13:31.435Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:13:31 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=151441408, heapTotal=116350976, heapUsed=74981656, external=26630091, loadavg=[2.18310546875, 1.7548828125, 1.41943359375], uptime=8832, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:13:54.497Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:13:54 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=152924160, heapTotal=119496704, heapUsed=74524824, external=21108199, loadavg=[2.11328125, 1.7744140625, 1.435546875], uptime=8855, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:14:13.796Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:14:13 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=148455424, heapTotal=112680960, heapUsed=74695072, external=26630091, loadavg=[1.92138671875, 1.7548828125, 1.43701171875], uptime=8874, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:14:33.876Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:14:33 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=148987904, heapTotal=113729536, heapUsed=74711720, external=26630091, loadavg=[1.72705078125, 1.7216796875, 1.43310546875], uptime=8894, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:23:47.763Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:23:47 GMT+0000 (UTC), pid=26, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=143228928, heapTotal=113205248, heapUsed=74129720, external=18270660, loadavg=[2.48193359375, 1.59423828125, 1.3251953125], uptime=9448, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:25:34.536Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:25:34 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=148738048, heapTotal=115912704, heapUsed=80867240, external=26630091, loadavg=[1.5263671875, 1.5, 1.318359375], uptime=9555, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:26:08.594Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:26:08 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=151011328, heapTotal=114339840, heapUsed=90493112, external=26630091, loadavg=[2.26171875, 1.6962890625, 1.392578125], uptime=9589, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:26:42.112Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:26:42 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=152920064, heapTotal=118972416, heapUsed=74478736, external=20999344, loadavg=[2.64599609375, 1.8525390625, 1.4560546875], uptime=9622, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T04:27:03.003Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 04:27:02 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=151531520, heapTotal=117399552, heapUsed=74464616, external=20885868, loadavg=[2.43310546875, 1.87744140625, 1.474609375], uptime=9643, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T22:08:44.477Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 22:08:44 GMT+0000 (UTC), pid=26, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=145666048, heapTotal=116350976, heapUsed=74205984, external=18270660, loadavg=[2.36865234375, 1.3154296875, 0.548828125], uptime=18383, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-16T22:09:02.391Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Sun Sep 16 2018 22:09:02 GMT+0000 (UTC), pid=16, uid=0, gid=0, cwd=/backend, execPath=/usr/local/bin/node, version=v8.11.2, argv=[/usr/local/bin/node, /backend], rss=151375872, heapTotal=117923840, heapUsed=74523656, external=20885868, loadavg=[2.0419921875, 1.310546875, 0.56396484375], uptime=18401, trace=[column=11, file=/backend/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/backend/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/backend/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/backend/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/backend/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-18T05:02:43.721Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue Sep 18 2018 05:02:43 GMT+0000 (UTC), pid=19, uid=0, gid=0, cwd=/usr/app, execPath=/usr/bin/node, version=v8.9.1, argv=[/usr/bin/node, /usr/app], rss=151089152, heapTotal=122228736, heapUsed=92220192, external=18270660, loadavg=[1.16552734375, 0.70947265625, 0.48681640625], uptime=7474, trace=[column=11, file=/usr/app/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/usr/app/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/usr/app/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/usr/app/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/usr/app/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/usr/app/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-18T05:05:24.658Z - error: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue Sep 18 2018 05:05:24 GMT+0000 (UTC), pid=18, uid=0, gid=0, cwd=/usr/app, execPath=/usr/bin/node, version=v8.9.1, argv=[/usr/bin/node, /usr/app], rss=143818752, heapTotal=115937280, heapUsed=86223776, external=26621128, loadavg=[0.56640625, 0.54345703125, 0.45068359375], uptime=7635, trace=[column=11, file=/usr/app/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/usr/app/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/usr/app/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/usr/app/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/usr/app/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/usr/app/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-18T05:10:07.270Z - error: uncaughtException: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo EAI_AGAIN mongo:27017] date=Tue Sep 18 2018 05:10:07 GMT+0000 (UTC), pid=19, uid=0, gid=0, cwd=/usr/app, execPath=/usr/bin/node, version=v8.9.1, argv=[/usr/bin/node, /usr/app], rss=164319232, heapTotal=135901184, heapUsed=84828912, external=20903227, loadavg=[0.23876953125, 0.37939453125, 0.408203125], uptime=7917, trace=[column=11, file=/usr/app/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/usr/app/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/usr/app/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo EAI_AGAIN mongo:27017],     at Pool.<anonymous> (/usr/app/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/usr/app/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/usr/app/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
2018-09-18T05:11:26.404Z - error: uncaughtException: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] date=Tue Sep 18 2018 05:11:26 GMT+0000 (UTC), pid=19, uid=0, gid=0, cwd=/usr/app, execPath=/usr/bin/node, version=v8.9.1, argv=[/usr/bin/node, /usr/app], rss=144719872, heapTotal=115937280, heapUsed=86398424, external=26621128, loadavg=[0.23828125, 0.33447265625, 0.38623046875], uptime=7996, trace=[column=11, file=/usr/app/node_modules/mongodb-core/lib/topologies/server.js, function=null, line=564, method=null, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=211, method=emit, native=false, column=12, file=/usr/app/node_modules/mongodb-core/lib/connection/pool.js, function=null, line=317, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=317, method=onceWrapper, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=214, method=emit, native=false, column=50, file=/usr/app/node_modules/mongodb-core/lib/connection/connection.js, function=null, line=246, method=null, native=false, column=30, file=events.js, function=Object.onceWrapper, line=315, method=onceWrapper, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=8, file=internal/streams/destroy.js, function=emitErrorNT, line=64, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=138, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=180, method=_tickCallback, native=false], stack=[MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017],     at Pool.<anonymous> (/usr/app/node_modules/mongodb-core/lib/topologies/server.js:564:11),     at emitOne (events.js:116:13),     at Pool.emit (events.js:211:7),     at Connection.<anonymous> (/usr/app/node_modules/mongodb-core/lib/connection/pool.js:317:12),     at Object.onceWrapper (events.js:317:30),     at emitTwo (events.js:126:13),     at Connection.emit (events.js:214:7),     at Socket.<anonymous> (/usr/app/node_modules/mongodb-core/lib/connection/connection.js:246:50),     at Object.onceWrapper (events.js:315:30),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at emitErrorNT (internal/streams/destroy.js:64:8),     at _combinedTickCallback (internal/process/next_tick.js:138:11),     at process._tickCallback (internal/process/next_tick.js:180:9)]
